In [29]:
import requests

In [30]:
url = 'https://api.quran.com/api/v4/search?q=jannat'

In [31]:
response = requests.get(url)

In [32]:
data = response.json()
data

{'search': {'query': 'jannat',
  'total_results': 2,
  'current_page': 1,
  'total_pages': 1,
  'results': [{'verse_key': '53:15',
    'verse_id': 4799,
    'text': 'عِندَهَا جَنَّةُ ٱلْمَأْوَىٰٓ',
    'highlighted': None,
    'words': [{'char_type': 'word', 'text': 'عِندَهَا'},
     {'char_type': 'word', 'text': 'جَنَّةُ'},
     {'char_type': 'word', 'text': 'ٱلۡمَأۡوَىٰٓ'},
     {'char_type': 'end', 'text': '١٥'}],
    'translations': [{'text': 'near which there is <em>Jannat</em>-ul-Ma’wā (the Paradise of Abode),',
      'resource_id': 84,
      'name': 'T. Usmani',
      'language_name': 'english'},
     {'text': "near which there is <em>Jannat</em>-ul-ma'wa (the Paradise of Abode),",
      'resource_id': 167,
      'name': 'Maarif-ul-Quran',
      'language_name': 'english'}]}]}}

In [33]:
import pandas as pd
df = pd.DataFrame(data['search']['results'][0]['translations'])
df.head()

,text,resource_id,name,language_name
0,near which there is <em>Jannat</em>-ul-Ma’wā (...,84,T. Usmani,english
1,near which there is <em>Jannat</em>-ul-ma'wa (...,167,Maarif-ul-Quran,english

In [34]:
# function remove <> and everthing in between
def remove_html_tags(text):
    import re
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [35]:
# remove from text
df['text_clean'] = df['text'].apply(remove_html_tags)
df.head()

,text,resource_id,name,language_name,text_clean
0,near which there is <em>Jannat</em>-ul-Ma’wā (...,84,T. Usmani,english,near which there is Jannat-ul-Ma’wā (the Parad...
1,near which there is <em>Jannat</em>-ul-ma'wa (...,167,Maarif-ul-Quran,english,near which there is Jannat-ul-ma'wa (the Parad...